/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.location.records;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.lusty.backend.location.records.tables.DeviceLastLocations;
import ru.lusty.backend.location.records.tables.DeviceLocations;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DEVICE_LOCATIONS_LAT_LNG = Internal.createIndex(DSL.name("device_locations_lat_lng"), DeviceLocations.DEVICE_LOCATIONS, new OrderField[] { DeviceLocations.DEVICE_LOCATIONS.LATITUDE, DeviceLocations.DEVICE_LOCATIONS.LONGITUDE }, false);
    public static final Index DEVICE_LOCATIONS_USER_ID_CREATED_AT = Internal.createIndex(DSL.name("device_locations_user_id_created_at"), DeviceLocations.DEVICE_LOCATIONS, new OrderField[] { DeviceLocations.DEVICE_LOCATIONS.USER_ID, DeviceLocations.DEVICE_LOCATIONS.CREATED_AT }, false);
    public static final Index IDX_DEVICE_LAST_LOCATIONS_DEVICE_ID = Internal.createIndex(DSL.name("idx_device_last_locations_device_id"), DeviceLastLocations.DEVICE_LAST_LOCATIONS, new OrderField[] { DeviceLastLocations.DEVICE_LAST_LOCATIONS.DEVICE_ID }, false);
    public static final Index IDX_DEVICE_LAST_LOCATIONS_USER_ID = Internal.createIndex(DSL.name("idx_device_last_locations_user_id"), DeviceLastLocations.DEVICE_LAST_LOCATIONS, new OrderField[] { DeviceLastLocations.DEVICE_LAST_LOCATIONS.USER_ID }, false);
}
