/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.location.records;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.lusty.backend.location.records.tables.DeviceLocations;
import ru.lusty.backend.location.records.tables.records.DeviceLocationsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DeviceLocationsRecord> DEVICE_LOCATIONS_PKEY = Internal.createUniqueKey(DeviceLocations.DEVICE_LOCATIONS, DSL.name("device_locations_pkey"), new TableField[] { DeviceLocations.DEVICE_LOCATIONS.ID }, true);
}
