/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.location.records;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.lusty.backend.location.records.tables.DeviceLastLocations;
import ru.lusty.backend.location.records.tables.DeviceLocations;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.device_last_locations</code>.
     */
    public final DeviceLastLocations DEVICE_LAST_LOCATIONS = DeviceLastLocations.DEVICE_LAST_LOCATIONS;

    /**
     * The table <code>public.device_locations</code>.
     */
    public final DeviceLocations DEVICE_LOCATIONS = DeviceLocations.DEVICE_LOCATIONS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DeviceLastLocations.DEVICE_LAST_LOCATIONS,
            DeviceLocations.DEVICE_LOCATIONS
        );
    }
}
