/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.location.records;


import ru.lusty.backend.location.records.tables.DeviceLastLocations;
import ru.lusty.backend.location.records.tables.DeviceLocations;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.device_last_locations</code>.
     */
    public static final DeviceLastLocations DEVICE_LAST_LOCATIONS = DeviceLastLocations.DEVICE_LAST_LOCATIONS;

    /**
     * The table <code>public.device_locations</code>.
     */
    public static final DeviceLocations DEVICE_LOCATIONS = DeviceLocations.DEVICE_LOCATIONS;
}
