/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.adminnotifier.records;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.lusty.backend.adminnotifier.records.tables.AdminTgChats;
import ru.lusty.backend.adminnotifier.records.tables.records.AdminTgChatsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdminTgChatsRecord> ADMIN_TG_CHATS_PKEY = Internal.createUniqueKey(AdminTgChats.ADMIN_TG_CHATS, DSL.name("admin_tg_chats_pkey"), new TableField[] { AdminTgChats.ADMIN_TG_CHATS.ID }, true);
}
