/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.adminnotifier.records;


import ru.lusty.backend.adminnotifier.records.tables.AdminTgChats;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.admin_tg_chats</code>.
     */
    public static final AdminTgChats ADMIN_TG_CHATS = AdminTgChats.ADMIN_TG_CHATS;
}
