spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/core
    username: backend
    password: idjcnqfgln
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: backend
    password: idjcnqfgln

db-scheduler.polling-interval: 1s
