/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.location.records.tables;


import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.lusty.backend.common.jooq.JooqInstantConverter;
import ru.lusty.backend.location.records.Indexes;
import ru.lusty.backend.location.records.Public;
import ru.lusty.backend.location.records.tables.records.DeviceLastLocationsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceLastLocations extends TableImpl<DeviceLastLocationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.device_last_locations</code>
     */
    public static final DeviceLastLocations DEVICE_LAST_LOCATIONS = new DeviceLastLocations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeviceLastLocationsRecord> getRecordType() {
        return DeviceLastLocationsRecord.class;
    }

    /**
     * The column <code>public.device_last_locations.id</code>.
     */
    public final TableField<DeviceLastLocationsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.device_last_locations.device_id</code>.
     */
    public final TableField<DeviceLastLocationsRecord, String> DEVICE_ID = createField(DSL.name("device_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.device_last_locations.user_id</code>.
     */
    public final TableField<DeviceLastLocationsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.device_last_locations.latitude</code>.
     */
    public final TableField<DeviceLastLocationsRecord, Double> LATITUDE = createField(DSL.name("latitude"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.device_last_locations.longitude</code>.
     */
    public final TableField<DeviceLastLocationsRecord, Double> LONGITUDE = createField(DSL.name("longitude"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.device_last_locations.created_at</code>.
     */
    public final TableField<DeviceLastLocationsRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0), this, "", new JooqInstantConverter());

    private DeviceLastLocations(Name alias, Table<DeviceLastLocationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private DeviceLastLocations(Name alias, Table<DeviceLastLocationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.materializedView());
    }

    /**
     * Create an aliased <code>public.device_last_locations</code> table
     * reference
     */
    public DeviceLastLocations(String alias) {
        this(DSL.name(alias), DEVICE_LAST_LOCATIONS);
    }

    /**
     * Create an aliased <code>public.device_last_locations</code> table
     * reference
     */
    public DeviceLastLocations(Name alias) {
        this(alias, DEVICE_LAST_LOCATIONS);
    }

    /**
     * Create a <code>public.device_last_locations</code> table reference
     */
    public DeviceLastLocations() {
        this(DSL.name("device_last_locations"), null);
    }

    public <O extends Record> DeviceLastLocations(Table<O> child, ForeignKey<O, DeviceLastLocationsRecord> key) {
        super(child, key, DEVICE_LAST_LOCATIONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_DEVICE_LAST_LOCATIONS_DEVICE_ID, Indexes.IDX_DEVICE_LAST_LOCATIONS_USER_ID);
    }

    @Override
    public DeviceLastLocations as(String alias) {
        return new DeviceLastLocations(DSL.name(alias), this);
    }

    @Override
    public DeviceLastLocations as(Name alias) {
        return new DeviceLastLocations(alias, this);
    }

    @Override
    public DeviceLastLocations as(Table<?> alias) {
        return new DeviceLastLocations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DeviceLastLocations rename(String name) {
        return new DeviceLastLocations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DeviceLastLocations rename(Name name) {
        return new DeviceLastLocations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DeviceLastLocations rename(Table<?> name) {
        return new DeviceLastLocations(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, UUID, Double, Double, Instant> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super UUID, ? super String, ? super UUID, ? super Double, ? super Double, ? super Instant, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super UUID, ? super String, ? super UUID, ? super Double, ? super Double, ? super Instant, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
