/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.common.broker.tables;


import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.lusty.backend.common.broker.Indexes;
import ru.lusty.backend.common.broker.Keys;
import ru.lusty.backend.common.broker.Public;
import ru.lusty.backend.common.broker.tables.records.OutgoingMessagesRecord;
import ru.lusty.backend.common.jooq.JooqInstantConverter;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OutgoingMessages extends TableImpl<OutgoingMessagesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.outgoing_messages</code>
     */
    public static final OutgoingMessages OUTGOING_MESSAGES = new OutgoingMessages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OutgoingMessagesRecord> getRecordType() {
        return OutgoingMessagesRecord.class;
    }

    /**
     * The column <code>public.outgoing_messages.id</code>.
     */
    public final TableField<OutgoingMessagesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.outgoing_messages.exchange</code>.
     */
    public final TableField<OutgoingMessagesRecord, String> EXCHANGE = createField(DSL.name("exchange"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.outgoing_messages.routing_key</code>.
     */
    public final TableField<OutgoingMessagesRecord, String> ROUTING_KEY = createField(DSL.name("routing_key"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.outgoing_messages.json</code>.
     */
    public final TableField<OutgoingMessagesRecord, String> JSON = createField(DSL.name("json"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.outgoing_messages.created_at</code>.
     */
    public final TableField<OutgoingMessagesRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "", new JooqInstantConverter());

    private OutgoingMessages(Name alias, Table<OutgoingMessagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private OutgoingMessages(Name alias, Table<OutgoingMessagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.outgoing_messages</code> table reference
     */
    public OutgoingMessages(String alias) {
        this(DSL.name(alias), OUTGOING_MESSAGES);
    }

    /**
     * Create an aliased <code>public.outgoing_messages</code> table reference
     */
    public OutgoingMessages(Name alias) {
        this(alias, OUTGOING_MESSAGES);
    }

    /**
     * Create a <code>public.outgoing_messages</code> table reference
     */
    public OutgoingMessages() {
        this(DSL.name("outgoing_messages"), null);
    }

    public <O extends Record> OutgoingMessages(Table<O> child, ForeignKey<O, OutgoingMessagesRecord> key) {
        super(child, key, OUTGOING_MESSAGES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.OUTGOING_MESSAGES_CREATED_AT);
    }

    @Override
    public UniqueKey<OutgoingMessagesRecord> getPrimaryKey() {
        return Keys.OUTGOING_MESSAGES_PKEY;
    }

    @Override
    public OutgoingMessages as(String alias) {
        return new OutgoingMessages(DSL.name(alias), this);
    }

    @Override
    public OutgoingMessages as(Name alias) {
        return new OutgoingMessages(alias, this);
    }

    @Override
    public OutgoingMessages as(Table<?> alias) {
        return new OutgoingMessages(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OutgoingMessages rename(String name) {
        return new OutgoingMessages(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OutgoingMessages rename(Name name) {
        return new OutgoingMessages(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OutgoingMessages rename(Table<?> name) {
        return new OutgoingMessages(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, String, String, Instant> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super UUID, ? super String, ? super String, ? super String, ? super Instant, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super UUID, ? super String, ? super String, ? super String, ? super Instant, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
