/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.profile.records.tables.records;


import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ru.lusty.backend.profile.api.Gender;
import ru.lusty.backend.profile.records.tables.Profiles;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfilesRecord extends UpdatableRecordImpl<ProfilesRecord> implements Record8<UUID, String, LocalDate, Gender, Boolean, Instant, Instant, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.profiles.id</code>.
     */
    public ProfilesRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.profiles.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.profiles.name</code>.
     */
    public ProfilesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.profiles.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.profiles.birthday</code>.
     */
    public ProfilesRecord setBirthday(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.profiles.birthday</code>.
     */
    public LocalDate getBirthday() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.profiles.gender</code>.
     */
    public ProfilesRecord setGender(Gender value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.profiles.gender</code>.
     */
    public Gender getGender() {
        return (Gender) get(3);
    }

    /**
     * Setter for <code>public.profiles.hidden</code>.
     */
    public ProfilesRecord setHidden(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.profiles.hidden</code>.
     */
    public Boolean getHidden() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.profiles.created_at</code>.
     */
    public ProfilesRecord setCreatedAt(Instant value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.profiles.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>public.profiles.deleted_at</code>.
     */
    public ProfilesRecord setDeletedAt(Instant value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.profiles.deleted_at</code>.
     */
    public Instant getDeletedAt() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>public.profiles.instagram</code>.
     */
    public ProfilesRecord setInstagram(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.profiles.instagram</code>.
     */
    public String getInstagram() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, String, LocalDate, Gender, Boolean, Instant, Instant, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, String, LocalDate, Gender, Boolean, Instant, Instant, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Profiles.PROFILES.ID;
    }

    @Override
    public Field<String> field2() {
        return Profiles.PROFILES.NAME;
    }

    @Override
    public Field<LocalDate> field3() {
        return Profiles.PROFILES.BIRTHDAY;
    }

    @Override
    public Field<Gender> field4() {
        return Profiles.PROFILES.GENDER;
    }

    @Override
    public Field<Boolean> field5() {
        return Profiles.PROFILES.HIDDEN;
    }

    @Override
    public Field<Instant> field6() {
        return Profiles.PROFILES.CREATED_AT;
    }

    @Override
    public Field<Instant> field7() {
        return Profiles.PROFILES.DELETED_AT;
    }

    @Override
    public Field<String> field8() {
        return Profiles.PROFILES.INSTAGRAM;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public LocalDate component3() {
        return getBirthday();
    }

    @Override
    public Gender component4() {
        return getGender();
    }

    @Override
    public Boolean component5() {
        return getHidden();
    }

    @Override
    public Instant component6() {
        return getCreatedAt();
    }

    @Override
    public Instant component7() {
        return getDeletedAt();
    }

    @Override
    public String component8() {
        return getInstagram();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public LocalDate value3() {
        return getBirthday();
    }

    @Override
    public Gender value4() {
        return getGender();
    }

    @Override
    public Boolean value5() {
        return getHidden();
    }

    @Override
    public Instant value6() {
        return getCreatedAt();
    }

    @Override
    public Instant value7() {
        return getDeletedAt();
    }

    @Override
    public String value8() {
        return getInstagram();
    }

    @Override
    public ProfilesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ProfilesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProfilesRecord value3(LocalDate value) {
        setBirthday(value);
        return this;
    }

    @Override
    public ProfilesRecord value4(Gender value) {
        setGender(value);
        return this;
    }

    @Override
    public ProfilesRecord value5(Boolean value) {
        setHidden(value);
        return this;
    }

    @Override
    public ProfilesRecord value6(Instant value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ProfilesRecord value7(Instant value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public ProfilesRecord value8(String value) {
        setInstagram(value);
        return this;
    }

    @Override
    public ProfilesRecord values(UUID value1, String value2, LocalDate value3, Gender value4, Boolean value5, Instant value6, Instant value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfilesRecord
     */
    public ProfilesRecord() {
        super(Profiles.PROFILES);
    }

    /**
     * Create a detached, initialised ProfilesRecord
     */
    public ProfilesRecord(UUID id, String name, LocalDate birthday, Gender gender, Boolean hidden, Instant createdAt, Instant deletedAt, String instagram) {
        super(Profiles.PROFILES);

        setId(id);
        setName(name);
        setBirthday(birthday);
        setGender(gender);
        setHidden(hidden);
        setCreatedAt(createdAt);
        setDeletedAt(deletedAt);
        setInstagram(instagram);
        resetChangedOnNotNull();
    }
}
