/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.profile.records.tables.records;


import java.time.Instant;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.lusty.backend.profile.records.tables.Verifications;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerificationsRecord extends UpdatableRecordImpl<VerificationsRecord> implements Record6<UUID, UUID, UUID, Instant, Boolean, Instant> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.verifications.id</code>.
     */
    public VerificationsRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.verifications.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.verifications.profile_id</code>.
     */
    public VerificationsRecord setProfileId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.verifications.profile_id</code>.
     */
    public UUID getProfileId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.verifications.file_id</code>.
     */
    public VerificationsRecord setFileId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.verifications.file_id</code>.
     */
    public UUID getFileId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.verifications.created_at</code>.
     */
    public VerificationsRecord setCreatedAt(Instant value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.verifications.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(3);
    }

    /**
     * Setter for <code>public.verifications.approved</code>.
     */
    public VerificationsRecord setApproved(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.verifications.approved</code>.
     */
    public Boolean getApproved() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.verifications.reviewed_at</code>.
     */
    public VerificationsRecord setReviewedAt(Instant value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.verifications.reviewed_at</code>.
     */
    public Instant getReviewedAt() {
        return (Instant) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, UUID, Instant, Boolean, Instant> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, UUID, Instant, Boolean, Instant> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Verifications.VERIFICATIONS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Verifications.VERIFICATIONS.PROFILE_ID;
    }

    @Override
    public Field<UUID> field3() {
        return Verifications.VERIFICATIONS.FILE_ID;
    }

    @Override
    public Field<Instant> field4() {
        return Verifications.VERIFICATIONS.CREATED_AT;
    }

    @Override
    public Field<Boolean> field5() {
        return Verifications.VERIFICATIONS.APPROVED;
    }

    @Override
    public Field<Instant> field6() {
        return Verifications.VERIFICATIONS.REVIEWED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getProfileId();
    }

    @Override
    public UUID component3() {
        return getFileId();
    }

    @Override
    public Instant component4() {
        return getCreatedAt();
    }

    @Override
    public Boolean component5() {
        return getApproved();
    }

    @Override
    public Instant component6() {
        return getReviewedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getProfileId();
    }

    @Override
    public UUID value3() {
        return getFileId();
    }

    @Override
    public Instant value4() {
        return getCreatedAt();
    }

    @Override
    public Boolean value5() {
        return getApproved();
    }

    @Override
    public Instant value6() {
        return getReviewedAt();
    }

    @Override
    public VerificationsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public VerificationsRecord value2(UUID value) {
        setProfileId(value);
        return this;
    }

    @Override
    public VerificationsRecord value3(UUID value) {
        setFileId(value);
        return this;
    }

    @Override
    public VerificationsRecord value4(Instant value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public VerificationsRecord value5(Boolean value) {
        setApproved(value);
        return this;
    }

    @Override
    public VerificationsRecord value6(Instant value) {
        setReviewedAt(value);
        return this;
    }

    @Override
    public VerificationsRecord values(UUID value1, UUID value2, UUID value3, Instant value4, Boolean value5, Instant value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VerificationsRecord
     */
    public VerificationsRecord() {
        super(Verifications.VERIFICATIONS);
    }

    /**
     * Create a detached, initialised VerificationsRecord
     */
    public VerificationsRecord(UUID id, UUID profileId, UUID fileId, Instant createdAt, Boolean approved, Instant reviewedAt) {
        super(Verifications.VERIFICATIONS);

        setId(id);
        setProfileId(profileId);
        setFileId(fileId);
        setCreatedAt(createdAt);
        setApproved(approved);
        setReviewedAt(reviewedAt);
        resetChangedOnNotNull();
    }
}
