/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.profile.records;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.lusty.backend.profile.records.tables.ProfilePhoto;
import ru.lusty.backend.profile.records.tables.Profiles;
import ru.lusty.backend.profile.records.tables.Verifications;
import ru.lusty.backend.profile.records.tables.records.ProfilePhotoRecord;
import ru.lusty.backend.profile.records.tables.records.ProfilesRecord;
import ru.lusty.backend.profile.records.tables.records.VerificationsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProfilePhotoRecord> PROFILE_PHOTO_PKEY = Internal.createUniqueKey(ProfilePhoto.PROFILE_PHOTO, DSL.name("profile_photo_pkey"), new TableField[] { ProfilePhoto.PROFILE_PHOTO.PROFILE_ID, ProfilePhoto.PROFILE_PHOTO.FILE_ID }, true);
    public static final UniqueKey<ProfilesRecord> PROFILES_PKEY = Internal.createUniqueKey(Profiles.PROFILES, DSL.name("profiles_pkey"), new TableField[] { Profiles.PROFILES.ID }, true);
    public static final UniqueKey<VerificationsRecord> VERIFICATIONS_PKEY = Internal.createUniqueKey(Verifications.VERIFICATIONS, DSL.name("verifications_pkey"), new TableField[] { Verifications.VERIFICATIONS.ID }, true);
}
