/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.profile.records;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.lusty.backend.profile.records.tables.ProfilePhoto;
import ru.lusty.backend.profile.records.tables.Profiles;
import ru.lusty.backend.profile.records.tables.Verifications;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.profile_photo</code>.
     */
    public final ProfilePhoto PROFILE_PHOTO = ProfilePhoto.PROFILE_PHOTO;

    /**
     * The table <code>public.profiles</code>.
     */
    public final Profiles PROFILES = Profiles.PROFILES;

    /**
     * The table <code>public.verifications</code>.
     */
    public final Verifications VERIFICATIONS = Verifications.VERIFICATIONS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ProfilePhoto.PROFILE_PHOTO,
            Profiles.PROFILES,
            Verifications.VERIFICATIONS
        );
    }
}
