/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.profile.records;


import ru.lusty.backend.profile.records.tables.ProfilePhoto;
import ru.lusty.backend.profile.records.tables.Profiles;
import ru.lusty.backend.profile.records.tables.Verifications;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.profile_photo</code>.
     */
    public static final ProfilePhoto PROFILE_PHOTO = ProfilePhoto.PROFILE_PHOTO;

    /**
     * The table <code>public.profiles</code>.
     */
    public static final Profiles PROFILES = Profiles.PROFILES;

    /**
     * The table <code>public.verifications</code>.
     */
    public static final Verifications VERIFICATIONS = Verifications.VERIFICATIONS;
}
