/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.profile.records.tables;


import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.lusty.backend.common.jooq.JooqInstantConverter;
import ru.lusty.backend.profile.records.Indexes;
import ru.lusty.backend.profile.records.Keys;
import ru.lusty.backend.profile.records.Public;
import ru.lusty.backend.profile.records.tables.records.VerificationsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Verifications extends TableImpl<VerificationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.verifications</code>
     */
    public static final Verifications VERIFICATIONS = new Verifications();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VerificationsRecord> getRecordType() {
        return VerificationsRecord.class;
    }

    /**
     * The column <code>public.verifications.id</code>.
     */
    public final TableField<VerificationsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.verifications.profile_id</code>.
     */
    public final TableField<VerificationsRecord, UUID> PROFILE_ID = createField(DSL.name("profile_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.verifications.file_id</code>.
     */
    public final TableField<VerificationsRecord, UUID> FILE_ID = createField(DSL.name("file_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.verifications.created_at</code>.
     */
    public final TableField<VerificationsRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "", new JooqInstantConverter());

    /**
     * The column <code>public.verifications.approved</code>.
     */
    public final TableField<VerificationsRecord, Boolean> APPROVED = createField(DSL.name("approved"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.verifications.reviewed_at</code>.
     */
    public final TableField<VerificationsRecord, Instant> REVIEWED_AT = createField(DSL.name("reviewed_at"), SQLDataType.LOCALDATETIME(6), this, "", new JooqInstantConverter());

    private Verifications(Name alias, Table<VerificationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Verifications(Name alias, Table<VerificationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.verifications</code> table reference
     */
    public Verifications(String alias) {
        this(DSL.name(alias), VERIFICATIONS);
    }

    /**
     * Create an aliased <code>public.verifications</code> table reference
     */
    public Verifications(Name alias) {
        this(alias, VERIFICATIONS);
    }

    /**
     * Create a <code>public.verifications</code> table reference
     */
    public Verifications() {
        this(DSL.name("verifications"), null);
    }

    public <O extends Record> Verifications(Table<O> child, ForeignKey<O, VerificationsRecord> key) {
        super(child, key, VERIFICATIONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.VERIFICATIONS_APPROVED, Indexes.VERIFICATIONS_PROFILE_ID);
    }

    @Override
    public UniqueKey<VerificationsRecord> getPrimaryKey() {
        return Keys.VERIFICATIONS_PKEY;
    }

    @Override
    public Verifications as(String alias) {
        return new Verifications(DSL.name(alias), this);
    }

    @Override
    public Verifications as(Name alias) {
        return new Verifications(alias, this);
    }

    @Override
    public Verifications as(Table<?> alias) {
        return new Verifications(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Verifications rename(String name) {
        return new Verifications(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Verifications rename(Name name) {
        return new Verifications(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Verifications rename(Table<?> name) {
        return new Verifications(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, UUID, Instant, Boolean, Instant> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super UUID, ? super UUID, ? super UUID, ? super Instant, ? super Boolean, ? super Instant, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super UUID, ? super UUID, ? super UUID, ? super Instant, ? super Boolean, ? super Instant, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
