/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.common.broker;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.lusty.backend.common.broker.tables.OutgoingMessages;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index OUTGOING_MESSAGES_CREATED_AT = Internal.createIndex(DSL.name("outgoing_messages_created_at"), OutgoingMessages.OUTGOING_MESSAGES, new OrderField[] { OutgoingMessages.OUTGOING_MESSAGES.CREATED_AT }, false);
}
