/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.common.broker;


import ru.lusty.backend.common.broker.tables.OutgoingMessages;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.outgoing_messages</code>.
     */
    public static final OutgoingMessages OUTGOING_MESSAGES = OutgoingMessages.OUTGOING_MESSAGES;
}
