/*
 * This file is generated by jOOQ.
 */
package ru.lusty.backend.location.records;


import ru.lusty.backend.location.records.tables.WebsocketSessions;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.websocket_sessions</code>.
     */
    public static final WebsocketSessions WEBSOCKET_SESSIONS = WebsocketSessions.WEBSOCKET_SESSIONS;
}
